package zeroencoder.validation;

public enum Error {
    INVALID_PARAMS,
    EMPTY_INPUT,
    CONTAINS_INVALID_CHARACTERS,
    NOT_CONTAINS_CORRECT_COMBINATION,
    NOT_ODD_COUNT_PARTS,
    INVALID_ENCODED_VALUE,
    INVALID_ENCODED_VALUE_FILL,
    CONTAINS_INVALID_BINARY
}
